import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Montserrat } from 'next/font/google';
import { Open_Sans } from 'next/font/google';
import "./globals.css";
// Leaflet global styles must be imported at the app root (Next.js requires global CSS here)
import "leaflet/dist/leaflet.css";
import Navbar from "@/components/Navbar";
import FuturisticFooter from "@/components/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const montserrat = Montserrat({
  weight: ['300', '400', '500', '700'], // Specify desired weights
  subsets: ['latin'], // Specify desired subsets
  display: 'swap', // Optimizes font loading
  variable: '--font-montserrat', // Optional: for use with CSS variables
});

const openSans = Open_Sans({
  subsets: ['latin'],
  weight: ['400', '600', '700'], // include the font weights you use
  display: 'swap',
  variable: '--font-open-sans',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={openSans.variable}>
      <body
        className="font-sans"
      // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        {/* <BackgroundMusic /> */}
        {children}
        <FuturisticFooter />
      </body>
    </html>
  );
}
